### ISSUE TITLE
More authorization params

### ISSUE THREAD

**Issue by sergiodxa-silverback** [danestves/remix-auth-auth0#21]
Latest OAuth2Strategy version has support to get the request URL params in the authorizationParams function, it could also be used here https://github.com/danestves/remix-auth-auth0/blob/8303c852585900333d191d724f0b9f720a252246/src/index.ts#L95-L104 to get the params from the request and use that to set the scope and audience and that way I could do `/auth0?screen_hint=singup&redirect_to=/home` and get those params passed to Auth0

**Comment by danestves** [comment]
Thanks for pointing out this, I release a new version with this feature 👉 https://github.com/danestves/remix-auth-auth0/releases/tag/v1.3.0
