### ISSUE TITLE
1.3.3 Doesn't include any javascript files

### ISSUE THREAD

**Issue by magicfoodhand** [danestves/remix-auth-auth0#52]
### Describe the bug

When upgrading to remix-auth-auth0 1.3.3

### Your Example Website or App

https://github.com/lavabear/remix-auth-auth0-example

### Steps to Reproduce the Bug or Issue

1. Create new project
2. Depend on remix-auth-auth0
3. npm install

### Expected behavior

As a user I expect there to be javascript files in this library release

### Screenshots or Videos

no javascript - ![Screen Shot 2022-03-08 at 10 25 57 AM](https://user-images.githubusercontent.com/31233652/157292787-1193dd43-4dd6-4afd-9d08-ee6f362ef05b.png)

### Platform

- OS: Linux, Mac
- Version: 1.3.3

**Comment by danestves** [comment]
Hi @magicfoodhand! Thank you for the report, a fix has been uploaded on the [v1.3.4](https://github.com/danestves/remix-auth-auth0/releases/tag/v1.3.4)

**Comment by magicfoodhand** [comment]
Thanks for the quick response!
