### ISSUE TITLE
"Feature Requests & Questions" link when opening an issue leads to a 404

### ISSUE THREAD

**Issue by MoSattler** [danestves/remix-auth-auth0#74]
### Describe the bug

"Feature Requests & Questions" link when opening an issue leads to a 404 and does not work
![Screenshot 2022-08-26 at 13 30 52](https://user-images.githubusercontent.com/64152453/186894526-a95ad435-8ef8-40d7-9179-921b9289d669.png)
.

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by danestves** [comment]
Fixed, thanks!
