### ISSUE TITLE
No support for hosted (Auth0Lock.js) log in

### ISSUE THREAD

**Issue by quuu** [danestves/remix-auth-auth0#92]
### Describe the bug

Hi, noticed that the only way to authenticate via auth0 is to redirect to their universal login page

Some apps I've seen have been using auth0lock.js which lets them embed the universal login widget onto a self-hosted page
https://github.com/auth0/lock

Will remix-auth-auth0 support a local embedded login? 

Seems like right now the main capability is to just authenticator.authenticate('auth0', request) which always redirects to the universal login page?

### Your Example Website or App

https://codesandbox.io/s/remix-run-examples-remix-auth-auth0-6rvc13

### Steps to Reproduce the Bug or Issue

create a remix app, add remix auth0 auth, see there's no way to have the authenticator strategy use the local form

### Expected behavior

Expected to be able to host the auth0 experience and authenticate

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by sergiodxa** [comment]
You don't need to use remix-auth-auth0 if you plan to use Auth0Lock.js, use the Auth0 SDK, grab the token and send it to a route where you can store it in a cookie/session yourself. There's nothing the Auth0Strategy for Remix Auth will give you in that case.

Note that, if you do that, you will have to ensure you correctly logout users on both the client-side SDK (it saves in localStorage) and the Remix app (cookie/session).
