### ISSUE TITLE
Support for Silent Authentication

### ISSUE THREAD

**Issue by lifeiscontent** [danestves/remix-auth-auth0#98]
### Describe the bug

https://auth0.com/docs/authenticate/login/configure-silent-authentication

my usecase would be for being able to switch between organizations seamlessly. https://community.auth0.com/t/switch-user-organisation-without-re-login/84183/3

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

have the ability to set `prompt=none` in a way that makes sense to support the usecase of switching between orgs.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lifeiscontent** [comment]
@sergiodxa is there currently a way to dynamically pass `prompt` to the `authenticator.authenticate` method? not sure about the security issues if any, but I imagine you'd want to do this via a query param to the auth callback route.

e.g.

`/auth/callback?prompt=none` which would in turn translate to something like

```ts
const url = new URL(request.url);
cosnt params = url.searchParams.get('prompt') === 'none' ? {prompt: 'none'} : undefined;
authenticator.authenticate('auth0', request, {
  context: {params}
})
```

**Comment by danestves** [comment]
Actually, right now, when you make a request to `/auth/auth0` (or whatever is the URL that you have for login) you can pass the prompt in query params, with that, you can start the silent authentication, I just tried using `?prompt=login` and that shows me the login screen of auth0 instead of the register one 👀 can you test it out?

**Comment by franklinjavier** [comment]
> Actually, right now, when you make a request to `/auth/auth0` (or whatever is the URL that you have for login) you can pass the prompt in query params, with that, you can start the silent authentication, I just tried using `?prompt=login` and that shows me the login screen of auth0 instead of the register one 👀 can you test it out?

This feature worked in version 1.7.0 but doesn't work in the current version. I tried with the `?login_hint=` param.

**Comment by lifeiscontent** [comment]
@franklinjavier just pushed a fix in the latest release, go ahead and try that out. @danestves I think this issue can be closed now.

**Comment by franklinjavier** [comment]
It worked, thank you

**Comment by danestves** [comment]
Awesome, thanks for confirming and thanks for the help @lifeiscontent
